version: "3.9"
services:
  db:
    image: postgres:16
    container_name: challenge-db
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U challenge -d challenge"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: challenge-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/challenge
      SPRING_DATASOURCE_USERNAME: challenge
      SPRING_DATASOURCE_PASSWORD: challenge
    ports:
      - "8080:8080"

volumes:
  db-data: